{
    'name' : 'Accidentally Ruined Product Disposal',
    'version' : '1.0.0',
    'author' : 'Rifat',
    'category' : 'Product disposal',
    'sequence' : 1,
    'summary' : 'Product Disposal',
    'description' : 'Product Disposal',
    'depends' : ['base', 'stock'],
    'data' : ['views/inept_product_view.xml',
                    'data/sequence.xml',
                    'security/ir.model.access.csv',
              ],
    'demo' : [],
    'installable' : True,
    'application' : True,
    'auto_install' : False,
    'asset' : {},
}